name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build wxwClub Main
        uses: docker/build-push-action@v6
        id: build-app
        with:
          context: .
          file: main.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wxwclub:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build wxwClub Worker
        uses: docker/build-push-action@v6
        id: build-worker
        with:
          context: .
          file: worker.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wxwclub-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
